/** Public asset paths — images live under /public/images */
export const ASSETS = {
  cover: "/images/cover/alliance-cover.jpg",
  back: "/images/cover/alliance-back.jpg",
  kickoffCover: "/images/cover/kickoff-cover.jpg",
  kickoffBack: "/images/cover/kickoff-back.jpg",
  proposalPdf: "/Alliance-Group-Motheo-Proposal.pdf",
  kickoffPdf: "/Alliance-Group-Motheo-Kickoff.pdf",
  enhancesoftProposalPdf: "/Enhancesoft-Proposal-Brian-Kimathi.pdf",
  enhancesoftCover: "/images/cover/enhancesoft-cover.jpg",
  enhancesoftBack: "/images/cover/enhancesoft-back.jpg",
  enhancesoftPartb: "/images/cover/enhancesoft-partb.jpg",
  brands: {
    allianceLogo: "/images/brands/alliance-logo.png",
    bweLogo: "/images/brands/bwe-logo.png",
    bweFavicon: "/images/brands/bwe-favicon.png",
    ibdFavicon: "/images/brands/favicon-ibd.png",
    ibdLogo: "/images/brands/ibd-logo-main.png",
    motheoLogo: "/images/brands/motheo-logo.png",
    enhancesoftLogo: "/images/brands/enhancesoft-icon.png",
    enhancesoftWordmark: "/images/brands/enhancesoft-wordmark.png",
    evolveLinkFavicon: "/images/brands/evolve-link-favicon.svg",
    clients: {
      mediapal: "/images/brands/clients/mediapal.png",
      safaricom: "/images/brands/clients/safaricom.png",
      yellowcard: "/images/brands/clients/yellowcard.png",
      evolve: "/images/brands/clients/evolve.png",
      ibd: "/images/brands/clients/ibd.png",
      ats: "/images/brands/clients/ats.png",
    },
  },
  consultantPortrait: "/images/consultants/brian-kimathi.png",
  inmindLive: "/images/portfolio/inmind/live.png",
  mediapalLive: "/images/portfolio/mediapal/live.png",
} as const;
