/** Public asset paths — images live under /public/images */
export const ASSETS = {
  cover: "/images/cover/alliance-cover.webp",
  back: "/images/cover/alliance-back.webp",
  kickoffCover: "/images/cover/kickoff-cover.webp",
  kickoffBack: "/images/cover/kickoff-back.webp",
  proposalPdf: "/Alliance-Group-Motheo-Proposal.pdf",
  kickoffPdf: "/Alliance-Group-Motheo-Kickoff.pdf",
  enhancesoftProposalPdf: "/Enhancesoft-Proposal-Brian-Kimathi.pdf",
  enhancesoftCover: "/images/cover/enhancesoft-cover.webp",
  enhancesoftBack: "/images/cover/enhancesoft-back.webp",
  enhancesoftPartb: "/images/cover/enhancesoft-partb.webp",
  brands: {
    allianceLogo: "/images/brands/alliance-logo.webp",
    bweLogo: "/images/brands/bwe-logo.webp",
    bweFavicon: "/images/brands/bwe-favicon.webp",
    ibdFavicon: "/images/brands/favicon-ibd.webp",
    ibdLogo: "/images/brands/ibd-logo-main.webp",
    motheoLogo: "/images/brands/motheo-logo.webp",
    enhancesoftLogo: "/images/brands/enhancesoft-icon.webp",
    enhancesoftWordmark: "/images/brands/enhancesoft-wordmark.webp",
    evolveLinkFavicon: "/images/brands/evolve-link-favicon.svg",
    clients: {
      mediapal: "/images/brands/clients/mediapal.webp",
      safaricom: "/images/brands/clients/safaricom.webp",
      yellowcard: "/images/brands/clients/yellowcard.webp",
      evolve: "/images/brands/clients/evolve.webp",
      ibd: "/images/brands/clients/ibd.webp",
      ats: "/images/brands/clients/ats.webp",
    },
  },
  consultantPortrait: "/images/consultants/brian-kimathi.webp",
  inmindLive: "/images/portfolio/inmind/live.webp",
  mediapalLive: "/images/portfolio/mediapal/live.webp",
} as const;
